apiVersion: v1
kind: Service
metadata:
  name: {{ include "apposto.fullname" . }}
  labels:
    {{- include "apposto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  clusterIP: None
  selector:
    {{- include "apposto.selectorLabels" . | nindent 4 }}
